name: "Run Security Scan"
description: "Run security scan on the codebase"
branding:
  icon: "code"
  color: "yellow"
inputs:
  wait:
    default: "1"
    description: "Wait time in seconds"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/runner-cleanup
    - name: Vulnerability scan
      id: govulncheck
      uses: golang/govulncheck-action@v1
      with:
        repo-checkout: false
